### ISSUE TITLE
get_version_v2() got an unexpected keyword argument 'auth'

### ISSUE THREAD

**Issue by anubhaskar** [anubhaskar/TrystackPython#1]
Traceback (most recent call last):
  File "list_flavors.py", line 17, in <module>
    flavors = driver.list_sizes()
  File "/usr/local/lib/python2.7/dist-packages/libcloud/compute/drivers/openstack.py", line 299, in list_sizes
    self.connection.request('/flavors/detail').object)
  File "/usr/local/lib/python2.7/dist-packages/libcloud/common/openstack.py", line 227, in request
    raw=raw)
  File "/usr/local/lib/python2.7/dist-packages/libcloud/common/base.py", line 753, in request
    action = self.morph_action_hook(action)
  File "/usr/local/lib/python2.7/dist-packages/libcloud/common/openstack.py", line 294, in morph_action_hook
    self._populate_hosts_and_request_paths()
  File "/usr/local/lib/python2.7/dist-packages/libcloud/common/openstack.py", line 327, in _populate_hosts_and_request_paths
    osa = osa.authenticate(**kwargs)  # may throw InvalidCreds
  File "/usr/local/lib/python2.7/dist-packages/libcloud/common/openstack_identity.py", line 852, in authenticate
    return self._authenticate_2_0_with_password()
  File "/usr/local/lib/python2.7/dist-packages/libcloud/common/openstack_identity.py", line 877, in _authenticate_2_0_with_password
    return self._authenticate_2_0_with_body(reqbody)
  File "/usr/local/lib/python2.7/dist-packages/libcloud/common/openstack_identity.py", line 882, in _authenticate_2_0_with_body
    method='POST')
  File "/usr/local/lib/python2.7/dist-packages/libcloud/common/base.py", line 862, in request
    response = responseCls(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/libcloud/common/base.py", line 179, in __init__
    headers=self.headers)
libcloud.common.exceptions.BaseHTTPError: {"error": {"message": "get_version_v2() got an unexpected keyword argument 'auth'", "code": 400, "title": "Bad Request"}}

**Comment by anubhaskar** [comment]
Issue resolved by making below changes:

1. Changed auth_url to "http://x.xx.xx.x:5000
2. Added "ex_tenant_name" option to connection creation arguments (driver)
